# Generated by Django 5.0.6 on 2024-09-03 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Wine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fixed_acidity', models.FloatField()),
                ('volatile_acidity', models.FloatField()),
                ('citric_acid', models.FloatField()),
                ('residual_sugar', models.FloatField()),
                ('chlorides', models.FloatField()),
                ('free_sulfur_dioxide', models.FloatField()),
                ('total_sulfur_dioxide', models.FloatField()),
                ('density', models.FloatField()),
                ('pH', models.FloatField()),
                ('sulphates', models.FloatField()),
                ('alcohol', models.FloatField()),
            ],
        ),
    ]
